### ISSUE TITLE
Warnings when used with @vue/test-utils v2.0.0-rc.4.

### ISSUE THREAD

**Issue by jgerigmeyer** [posva/vue-router-mock#96]
### Reproduction

After upgrading to [@vue/test-utils@2.0.0-rc.4](https://github.com/vuejs/vue-test-utils-next/releases/tag/v2.0.0-rc.4), tests pass but with warnings about `RouterView` and `RouterLink` components having already been registered.

### Steps to reproduce the behavior

Dependencies:

- "vue-router-mock": "0.0.2"
- "@vue/test-utils": "2.0.0-rc.4"

Config (in Jest setup file):

```
import { config } from '@vue/test-utils';
import {
  createRouterMock,
  injectRouterMock,
  VueRouterMock,
} from 'vue-router-mock';

const router = createRouterMock();
config.plugins.VueWrapper.install(VueRouterMock);

beforeEach(() => {
  injectRouterMock(router);
});
```

### Expected behavior

Tests pass with no warnings.

### Actual behavior

Tests pass, with warnings:

```
    console.warn
      [Vue warn]: Component "RouterView" has already been registered in target app.

      45 |
      46 |   it('passes', async () => {
    > 47 |     const { findByText } = render(MyComponent, {
         |                            ^
      48 |       props: { id: 'test' },

      at warn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40:17)
      at Object.component (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3050:21)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:2326:21)
      at render (node_modules/@testing-library/vue/dist/render.js:43:38)
      at Object.<anonymous> (tests/js/components/MyComponent.test.js:47:28)
```

```
    console.warn
      [Vue warn]: Component "RouterLink" has already been registered in target app.

      45 |
      46 |   it('passes', async () => {
    > 47 |     const { findByText } = render(MyComponent, {
         |                            ^
      48 |       props: { id: 'test' },

      at warn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40:17)
      at Object.component (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3050:21)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:2326:21)
      at render (node_modules/@testing-library/vue/dist/render.js:43:38)
      at Object.<anonymous> (tests/js/components/MyComponent.test.js:47:28)
```

**Comment by posva** [comment]
Probably introduced by https://github.com/vuejs/vue-test-utils-next/pull/438

Seems to still work but it shouldn't warn. I will take a look

**Comment by posva** [comment]
Will be fixed in the next vue-test-utils release!
